#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/workeezy?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    username: workeezy
#    password: your_password_here
#
#  jpa:
#    hibernate:
#      ddl-auto: none  # create, update, validate, none 중 선택
#    show-sql: true  # SQL 쿼리 콘솔 출력
#    properties:
#      hibernate:
#        format_sql: true  # SQL 포맷팅
#        dialect: org.hibernate.dialect.MySQL8Dialect
#    open-in-view: false  # OSIV 비활성화 (선택)
#
#logging:
#  level:
#    org.hibernate.SQL: debug  # SQL 로깅
#    org.hibernate.type.descriptor.sql.BasicBinder: trace  # 파라미터 값 로깅


# 수정할거에요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

